### ISSUE TITLE
你好，安卓8不能用吗

### ISSUE THREAD

**Issue by snltty** [TGSAN/MirrorCaster#1]
如题，我手机内核版本8.1    开了开发者选项，还是不能投屏成功，
是我操作有问题吗

**Comment by snltty** [comment]
![1](https://user-images.githubusercontent.com/10977033/91650618-5b009880-eab4-11ea-8770-2f0187191af3.png)
![2](https://user-images.githubusercontent.com/10977033/91650621-5e941f80-eab4-11ea-9ace-9a7182a4b4ad.png)

**Comment by snltty** [comment]
电源键   返回   音量 那些按键可以正常使用

**Comment by TGSAN** [comment]
可以检查一下mpv是否可以正常运行
